spring.application.name=sbeam

spring.datasource.url=jdbc:mysql://localhost:3308/sbeam?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=ChangeThisVerySecretAndLongEnough1234567890
jwt.expiration=3600


#
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.password=